apiVersion: apps/v1
kind: Deployment
metadata:
  name: netconf-driver
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: netconf-driver
  template:
    metadata:
      labels:
        app: netconf-driver
        part-of: lm
    spec:
{{- if .Values.app.affinity }}
      affinity:
{{ toYaml .Values.app.affinity | indent 8 }}
{{- end }}
{{- if .Values.app.tolerations }}
      tolerations:
{{ toYaml .Values.app.tolerations | indent 8 }}
{{- end }}
      containers:
        - name: netconf-driver
          image: {{ .Values.docker.image }}:{{ .Values.docker.version }}
          imagePullPolicy: Always
          securityContext: {}
          ports:
          - containerPort: 7139
            protocol: TCP
          {{- if .Values.app.livenessProbe.enabled }}
          livenessProbe:
            failureThreshold: {{ .Values.app.livenessProbe.failureThreshold }}
            httpGet:
              path: /management/health
              port: 7139
              scheme: {{- if .Values.app.config.security.ssl.enabled }} HTTPS {{- else }} HTTP {{- end }}
            initialDelaySeconds: {{ .Values.app.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.livenessProbe.periodSeconds }}
          {{- end }}
          {{- if .Values.app.readinessProbe.enabled }}
          readinessProbe:
            failureThreshold: {{ .Values.app.readinessProbe.failureThreshold }}
            httpGet:
              path: /management/health
              port: 7139
              scheme: {{- if .Values.app.config.security.ssl.enabled }} HTTPS {{- else }} HTTP {{- end }}
            initialDelaySeconds: {{ .Values.app.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.readinessProbe.periodSeconds }}         
          {{- end }}
          envFrom:
          - configMapRef:
              name: netconf-driver-env
          resources:
{{ toYaml .Values.app.resources | indent 12 }}   
          volumeMounts:
          - name: config
            mountPath: /var/netconfdriver/netconfdriver_config.yml
            subPath: netconfdriver_config.yml
          {{- if and .Values.app.config.security.ssl.enabled .Values.app.config.security.ssl.secret.name }}
          - name: {{ .Values.app.config.security.ssl.secret.name }}
            mountPath: /var/netconfdriver/certs
          {{- end }}
      volumes:
      - name: config
        configMap:
          name: netconf-driver
      {{- if and .Values.app.config.security.ssl.enabled .Values.app.config.security.ssl.secret.name }}
      - name: {{ .Values.app.config.security.ssl.secret.name }}
        secret:
          secretName: {{ .Values.app.config.security.ssl.secret.name }}
      {{- end }}
{{- if .Values.app.autoscaler.enabled }}
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: netconf-driver
spec:
  maxReplicas: {{ .Values.app.autoscaler.maxReplicas }}
  minReplicas: {{ .Values.app.autoscaler.minReplicas }}
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: netconf-driver
  targetCPUUtilizationPercentage: {{ .Values.app.autoscaler.targetCPUUtilizationPercentage }}
{{- end }}