apiVersion: v1
kind: Service
metadata:
  name: netconf-driver
  labels:
    app: netconf-driver
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 7139
    targetPort: 7139
{{- if eq .Values.service.type "NodePort" }}
    nodePort: {{ .Values.service.nodePort }}
{{- end }}
    protocol: TCP
    name: http
  selector:
    app: netconf-driver